FROM rust:1.88

RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-watch --locked

WORKDIR /app
COPY . .

EXPOSE 50051

CMD ["cargo", "watch", "-x", "run"]
